#!/bin/bash
#
# Init repo's ci configuration with template, include Makefile, Dockfile and Jenkinsfile in devops directory

readonly REPO_ACCOUNT=$(echo $1 |awk -F '/' '{print $1}')
readonly REPO_NAME=$(echo $1 |awk -F '/' '{print $2}')
readonly REPO_TYPE=$2
readonly JENKINS_CREDENTIALSID="devops-longguikeji-github-token"
readonly JENKINS_DEVOPS_ACCOUNT="admin"
readonly GITHUB_CREDENCIAL=$3
readonly GITHUB_SETTINGS_TOKEN=$4
readonly JENKINS_CREDENCIAL=$5

help() {
  echo """
  Script execute failed.
  Usage:
  For example:
      Repo URL: https://github.com/longguikeji/arkid-core.git
      Repo type: ts or python
      Run command below to init ci configure:
        ./ci_init longguikeji/arkid-core python github_credential github_settings_token jenkins_credential
  """
}

err() {
  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >&2
  help
}

cleanup() {
  rm -f Dockerfile
  rm -rf devops/
  rm -f Makefile
  rm -rf ${REPO_NAME}
  rm -f config.xml
}

initMakefile() {
  echo "begin initMakefile"

  sed "s/template_repo_name/${REPO_NAME}/g" devops.template/Makefile > Makefile
  if [ ${REPO_TYPE} == 'ts' ]; then
    sed -e "s/lint-template/npx lint-staged/" -e "s/test-template/npm run test:unit/" Makefile > Makefile.bak
    mv Makefile.bak Makefile
  elif [ ${REPO_TYPE} == 'python' ]; then
    sed -e "s/lint-template/.git\/hooks\/pre-commit/" \
    -e "s/test-template/python manage.py migrate \&\& python manage.py test siteapi.v1.tests/" Makefile > Makefile.bak
    mv Makefile.bak Makefile
  else
    err "Repo type not supported. Please use ts or python."
    cleanup
    exit -1
  fi

  echo "end initMakefile"
}

initDockerfile() {
  echo "begin initDockerfile"

  if [ ${REPO_TYPE} == 'ts' ]; then
    cp devops.template/Dockerfile.typescript Dockerfile
  elif [ ${REPO_TYPE} == 'python' ]; then
    cp devops.template/Dockerfile.python Dockerfile
  else
    err "Repo type not supported. Please use ts or python."
    cleanup
    exit -1
  fi

  echo "end initDockerfile"
}

initJenkinsfile() {
  echo "begin initJenkinsfile"

  mkdir devops
  cp devops.template/Jenkinsfile.* devops/
  sed "s/template_repo_name/${REPO_NAME}/g" devops/Jenkinsfile.release > devops/Jenkinsfile.release.bak
  mv devops/Jenkinsfile.release.bak devops/Jenkinsfile.release

  echo "end initJenkinsfile"
}

createCIInitBranch() {
  echo "begin createCIInitBranch"
  git clone https://github.com/${REPO_ACCOUNT}/${REPO_NAME}.git
  cd ${REPO_NAME}
  git config -l
  git checkout -b ci_init
  cp ../Dockerfile .
  cp -r ../devops .
  cp ../Makefile .
  git add .
  git commit -m 'auto init ci config'
  git push https://${GITHUB_CREDENCIAL}@github.com/${REPO_ACCOUNT}/${REPO_NAME}.git ci_init:ci_init
  cd ..

  echo "end createCIInitBranch"
}

createJob() {
  echo "begin createJob"

  create_status=$(curl -s -X POST -H "$2" http://localhost:8080/createItem?name=${REPO_NAME}.$1 \
  --data-binary "@config.xml" -H "Content-Type: text/xml" -u "${JENKINS_CREDENCIAL}")
  if [[ -n ${create_status} ]]; then
    err "CreateJob create failed. Detail: ${create_status}"
    cleanup
    exit -1
  fi
  echo "end createJob"
}

createJenkinsJobs() {
  echo "begin createJenkinsJobs"

  # using a crumb token when "Prevent Cross Site Request Forgery exploits" security option is enabled
  crumb=$(curl -s 'http://localhost:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)' -u "${JENKINS_CREDENCIAL}")
  crumb_status=$(echo ${crumb} | grep -c 'Jenkins-Crumb')
  if [[ ${crumb_status} == 0 ]]; then
    err "CreateJob get crumb failed. Detail: ${crumb}"
    cleanup
    exit -1
  fi

  sed -e "s/template_project_url/https:\/\/github.com\/${REPO_ACCOUNT}\/${REPO_NAME}\//" \
  -e "s/template_credentials_id/${JENKINS_CREDENTIALSID}/" \
  -e "s/template_repo_url/https:\/\/github.com\/${REPO_ACCOUNT}\/${REPO_NAME}.git/" \
  -e "s/template_branch_name/\*\*/" \
  -e "s/template_jenkinsfile_path/devops\/Jenkinsfile.status/" \
  devops.template/config.xml > config.xml

  createJob status ${crumb}

  sed -e "s/template_project_url/https:\/\/github.com\/${REPO_ACCOUNT}\/${REPO_NAME}\//" \
  -e "s/template_credentials_id/${JENKINS_CREDENTIALSID}/" \
  -e "s/template_repo_url/https:\/\/github.com\/${REPO_ACCOUNT}\/${REPO_NAME}.git/" \
  -e "s/template_branch_name/master/" \
  -e "s/template_jenkinsfile_path/devops\/Jenkinsfile.build/" \
  devops.template/config.xml > config.xml

  createJob build ${crumb}

  sed -e "s/template_project_url/https:\/\/github.com\/${REPO_ACCOUNT}\/${REPO_NAME}\//" \
  -e "s/template_credentials_id/${JENKINS_CREDENTIALSID}/" \
  -e "s/template_repo_url/https:\/\/github.com\/${REPO_ACCOUNT}\/${REPO_NAME}.git/" \
  -e "s/template_branch_name/master/" \
  -e "s/template_jenkinsfile_path/devops\/Jenkinsfile.release/" \
  devops.template/config.release.xml > config.xml

  createJob release ${crumb}

  echo "end createJenkinsJobs"
}

initRepoSettings() {
  echo "begin initRepoSettings"

  branch_settings='{
    "required_status_checks": {
      "strict": true,
      "contexts": [
        "'"${REPO_NAME}.status"'"
      ]
    },
    "enforce_admins": false,
    "required_pull_request_reviews": {
      "dismiss_stale_reviews": true,
      "require_code_owner_reviews": false,
      "required_approving_review_count": 1
    },
    "restrictions": null
  }'
  hook_settings='{
    "name": "web",
    "active": true,
    "events": [
      "push",
      "pull_request"
    ],
    "config": {
      "url": "https://ci.intra.longguikeji.com/github-webhook",
      "content_type": "json",
      "insecure_ssl": "0"
    }
  }'

  # set master branch rules
  curl -H "Content-type: application/json" -H "Accept: application/vnd.github.luke-cage-preview+json" \
  -H "Authorization: token ${GITHUB_SETTINGS_TOKEN}" \
  -d "${branch_settings}" \
  -X PUT https://api.github.com/repos/${REPO_ACCOUNT}/${REPO_NAME}/branches/master/protection

  # set repo webhooks
  curl -H "Content-type: application/json" \
  -H "Authorization: token ${GITHUB_SETTINGS_TOKEN}" \
  -d "${hook_settings}" \
  -X POST https://api.github.com/repos/${REPO_ACCOUNT}/${REPO_NAME}/hooks

  echo "end initRepoSettings"
}

if [[ $# < 5 ]]; then
  err "Params number invalid."
  exit -1
fi

if [[ -z ${REPO_NAME} ]]; then
  err "Repo url invalid."
  exit -1
fi

git config -l
initMakefile
initDockerfile
createJenkinsJobs
initJenkinsfile
createCIInitBranch
initRepoSettings
cleanup




